
file(READ "${CMAKE_CURRENT_LIST_DIR}/dbSchema.sql" dbschema_raw)
string(REGEX REPLACE "([^\r\n]*)[\r\n]+" "\"\\1\"\n" dbschema "${dbschema_raw}")

string(REGEX REPLACE "[ \t\r\n]" "" dbschema_for_hash "${dbschema_raw}")
string(SHA1 schema_hash "${dbschema_for_hash}")

FILE(WRITE ${CMAKE_CURRENT_BINARY_DIR}/karereDbSchema.cpp
 "//This file is autogenerated from src/dbSchema.sql\n\n"
 "namespace karere\n"
 "{\n"
 "const char* gDbSchema =\n${dbschema};\n"
 "const char* gDbSchemaHash = \"${schema_hash}\";\n"
 "}\n"
 )

