cmake_minimum_required(VERSION 2.8)

file(READ "${CMAKE_CURRENT_LIST_DIR}/dbSchema.sql" dbschema_raw)
string(REGEX REPLACE "([^\r\n]*)[\r\n]+" "\"\\1\"\n" dbschema "${dbschema_raw}")

FILE(WRITE ${CMAKE_CURRENT_BINARY_DIR}/karereDbSchema.cpp
 "//This file is autogenerated from src/dbSchema.sql\n\n"
 "namespace karere\n{\nconst char* gKarereDbSchema =\n${dbschema};\n}")

